/* wiki-plugin-plugman (as plugman) - 0.1.0 - Sun, 09 Aug 2026 16:16:29 GMT */
(()=>{var d="plugman";var L=s=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"),A=function(s){let t=[],a=function(y){let u=t.length;return t.push(y),`\u3016${u}\u3017`},o=(y,u)=>t[+u],c=function(y,u){let i=wiki.asSlug(u),p=u===u.trim()?"internal":"internal spaced";return i.length?a(`<a class="${p}" href="/${i}.html" data-page-name="${i}" title="view">${L(u)}</a>`):y},w=(y,u,i)=>a(`"<a class="external" target="_blank" href="${u}" title="${u}" rel="nofollow">${L(u)}</a>"`);return s=s.replace(/〖(\d+)〗/g,"\u3016 $1 \u3017").replace(/\[\[([^\]]+)\]\]/gi,c).replace(/"((http|https|ftp):.*?)"/gi,w),L(s).replace(/〖(\d+)〗/g,o)},N=function(s,t){let a={gray:"#ccc",red:"#f55",yellow:"#fb0",green:"#0e0"};return s!=null&&t!=null?s===t?a.green:a.yellow:t!=null?a.red:a.gray},E,M=function(s,t,a){let o="installed",c=e=>s.publish.find(r=>r.plugin===e),w=function(e,r,f){let l=r.plugin,h=r.birth?((Date.now()-r.birth)/1e3/3600/24/31.5).toFixed(0):"",b=function(){let S=r.package!=null?r.package.version:void 0,n=c(l).npm?.version;return N(S,n)},m=[`<tr class=row data-name=${r.plugin}>`];for(o of e.columns)m.push((()=>{switch(o){case"status":return`<td title=status style='text-align:center; color: ${b()}'>\u25C9`;case"name":return`<td title=name> ${l}`;case"menu":return`<td title=menu> ${(r.factory!=null?r.factory.category:void 0)||""}`;case"pages":return`<td title=pages style='text-align:center;'>${(r.pages!=null?r.pages.length:void 0)||""}`;case"service":return`<td title=service style='text-align:center;'>${h}`;case"bundled":return`<td title=bundled> ${f["wiki-plugin-"+l]||""}`;case"installed":return`<td title=installed> ${(r.package!=null?r.package.version:void 0)||""}`;case"published":return`<td title=published> ${c(l).npm?.version||""}`}})());return m.join(`
`)},y=function(e,r,f){let l,h=function(n){for(l of r)if(l.plugin===n)return l;return{plugin:n}},b=e.plugins.length>0?e.plugins.map(h):r,m=(()=>{let n=[];for(o of e.columns)n.push(`<td style='font-size:75%; color:gray;'>${o}`);return n})().join(`
`),S=(()=>{let n=[];for(let v=0;v<b.length;v++)l=b[v],n.push(w(e,l,f));return n})().join(`
`);return`<center> <p><img src="/favicon.png" width=16> <span style="color:gray;">${window.location.host}</span></p> <table style="width:100%;"><tr> ${m} ${S}</table> <button class=restart>restart</button> </center>`},u=function(e,r){let f;if(r==null)return`<p>can't find wiki-plugin-${e.plugin} in <a href=//npmjs.com target=_blank>npmjs.com</a></p>`;let l=t.find(`table [data-name=${e.plugin}]`),h=function(n){let v=s.install.indexOf(e);s.install[v]=e=n.row,l.find("[title=status]").css("color",N(n.installed,r.version)),l.find("[title=menu]").text((e.factory!=null?e.factory.category:void 0)||""),l.find("[title=pages]").text((e.pages!=null?e.pages.length:void 0)||""),l.find("[title=service]").text("0"),l.find("[title=installed]").text((e.package!=null?e.package.version:void 0)||""),t.find("button.restart").removeAttr("disabled").show()};window.plugins[d].install=async function(n){try{let v={method:"POST",body:JSON.stringify({version:n,plugin:e.plugin}),headers:{"Content-Type":"application/json"}},D=await fetch(`/plugin/${d}/install`,v).then(I=>I.json());h(D),l.find("[title=status]").css("color","white"),E.close()}catch{t.find("p").html("server error")}};let b=function(n){return typeof n=="string"?[n]:n},m=function(n){let v=()=>`<button onclick=window.plugins.${d}.install('${n}')> install </button>`;return`<tr> <td> ${n} <td> ${n===(e.package!=null?e.package.version:void 0)?"installed":v()}`},S=(()=>{let n=[];for(f of b(r.versions).reverse())n.push(m(f));return n})();return`<h3>${r.description}</h3> <p>Choose a version to install.</p> <table>${S.join(`
`)}`},i=function(e,r){let f=s.install.find(n=>n.plugin===e),l=function(n){return n?A(n).replace(/\n/g,"<br>"):""},h=function(n){return n?`<pre>${A(JSON.stringify(n,null,"  "))}</pre>`:""},b=n=>`<p><b><a href=#>${n.title}</a></b><br>${A(n.synopsis)}</p>`,m=function(n){return n?new Date(n).toString():"built-in"},S=n=>$.getJSON(`/plugin/${d}/view/${e}`,n);switch(o){case"status":return S(n=>r(u(f,n)));case"name":return r(l(f.authors));case"menu":return r(h(f.factory));case"pages":return r(f.pages.map(b).join(""));case"service":return r(m(f.birth));case"bundled":return r(h(s.bundle.data.dependencies));case"installed":return r(h(f.package));case"published":return r(h(c(e).npm||""));default:return r("unexpected column")}},p=function(e){let f=$(e.target).parent().data("name");return i(f,function(l){if(o==="status")return t.find("dialog").remove(),t.append(`<dialog>
  ${l}
</dialog>`),E=t.find("dialog")[0],console.log("dialog",E),E.showModal();{let h=t.parents(".page").data("key"),b=wiki.lineup.atKey(h).getContext(),m=window.open(`/plugins/${d}/dialog/#`,d,"popup,height=600,width=800");return m.location.pathname!==`/plugins/${d}/dialog/`?m.addEventListener("load",S=>m.postMessage({column:o,title:`${f} plugin ${o}`,body:l||"",pageKey:h,context:b},window.origin)):m.postMessage({column:o,title:`${f} plugin ${o}`,body:l||"",pageKey:h,context:b},window.origin)}})},g=function(e){if(e.shiftKey)return p(e)},x=function(e){return g(e),$(e.currentTarget).css("background-color","#f8f8f8")},k=e=>$(e.currentTarget).css("background-color","#eee");t.find("p").html(y(a,s.install,s.bundle.data.dependencies)),t.find(".row").on({mouseenter:x,mouseleave:k}),t.find("p td").on("click",function(e){return o=$(e.target).attr("title"),p(e)}),t.find("button.restart").hide().on("click",e=>{t.find("button.restart").attr("disabled","disabled");try{fetch(`/plugin/${d}/restart`,{method:"POST"})}catch{t.find("p").html("server error")}})};function T(s,t){let a=s.install,o=t.get(0).querySelector("p"),c=["format","data","other","system","option"],w=["activity","changes","factory","flagmatic","journalmatic","future","image","paragraph","present","recycler","reference","register"];o.innerHTML=c.map(i=>`
    <h3>${i}</h3>
    ${a.filter(p=>{let g=p.factory?.category;return w.includes(p.plugin)?i=="system":i==(g||"option")}).toSorted((p,g)=>p.plugin.localeCompare(g.plugin)).map(y).join(`
`)}`);function y(i){return`
      <details>
        <summary><a href=# style="text-decoration: none;">
          ${i.plugin}</a> \u2014 ${i.factory?.title??'<i style="color:#888">missing</i>'}
        </summary>
        ${u(i)}
      </details>
    `}function u(i){function p(k){return k.replaceAll(/&/g,"&amp;").replaceAll(/</g,"&lt;").replaceAll(/>/g,"&gt;").replaceAll(/\[\[(.*?)\]\]/g,"$1").replaceAll(/\[.*? (.*?)\]/g,"$1")}let g=(i.pages||[]).map(k=>`
      <p><a href=# style="text-decoration: none;" data-slug=${k.slug}>
          ${k.title}</a> \u2014 ${p(k.synopsis??"")}
      </p>
    `).join(`
`),x={author:i?.package.author,contributors:i?.package.contributors,version:i?.package.version,repository:i?.package.repository};return`
      <hr>
      ${g}
      <details><summary>more ...</summary>
        <pre>${JSON.stringify(x,null,2)}</pre>
      </details>
      <hr>`}for(let i of o.querySelectorAll("a"))i.addEventListener("click",p=>{p.preventDefault();let g=p.target,x=g.innerText.trim(),k=g.dataset?.slug?g.dataset.slug:`about-${x}-plugin`,e=p.shiftKey?null:$(g.closest(".page"));wiki.doInternalLink(k,e)})}var O=function(s){let t={columns:[],plugins:[],features:[]},a=(s||"").split(/\n+/);for(var o of a){var c;o.match(/\bSTATUS\b/)&&t.columns.push("status"),o.match(/\bNAME\b/)&&t.columns.push("name"),o.match(/\bMENU\b/)&&t.columns.push("menu"),o.match(/\bPAGES\b/)&&t.columns.push("pages"),o.match(/\bSERVICE\b/)&&t.columns.push("service"),o.match(/\bBUNDLED\b/)&&t.columns.push("bundled"),o.match(/\bINSTALLED\b/)&&t.columns.push("installed"),o.match(/\bPUBLISHED\b/)&&t.columns.push("published"),o.match(/\bBROWSE\b/)&&t.features.push("browse"),(c=o.match(/^wiki-plugin-(\w+)$/))&&t.plugins.push(c[1])}return t.columns.length===0&&(t.columns=t.plugins.length===0?["name","pages","menu","bundled","installed"]:["status","name","pages","bundled","installed","published"]),t},P=async function(s,t){let a=O(t.text);s.append(`<p style="background-color:#eee;padding:15px;">
  loading plugin details
</p>`);let o=c=>{a.features.includes("browse")?T(c,s):M(c,s,a)};try{if(a.plugins.length){let c={method:"POST",body:JSON.stringify(a),headers:{"Content-Type":"application/json"}};o(await fetch(`/plugin/${d}/plugins`,c).then(w=>w.json()))}else o(await fetch(`/plugin/${d}/plugins`).then(c=>c.json()))}catch{s.find("p").html("server error")}},C=(s,t)=>s.on("dblclick",()=>wiki.textEditor(s,t)),j=function(s){if(!s.source.opener||s.source.location.pathname!==`/plugins/${d}/dialog/`)return;console.log(`${d} listener`,s);let{data:t}=s,{action:a}=t;if(a==="doInternalLink"){var o=t.keepLineup,c=o??!1,w=t.pageKey,y=w??null,u=t.title,i=u??null,p=t.context,g=p??null,x=null;y!==null&&(x=c?null:$(".page").filter((k,e)=>$(e).data("key")===y)),wiki.pageHandler.context=g,wiki.doInternalLink(i,x)}else return console.error({where:`${d}Listener`,message:"unknown action",data:t})};if(typeof window<"u"&&window!==null){let s=`${d}Listener`;(typeof window[s]>"u"||window[s]===null)&&(console.log(`*** ${d} - Adding Message Listener`),window[s]=j,window.addEventListener("message",j))}typeof window<"u"&&(window.plugins[d]={emit:P,bind:C});var q=typeof window>"u"?{parse:O}:void 0;})();
//# sourceMappingURL=plugman.js.map
